/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicinasKabinetaPacientuSistema;

/**
 *
 * @author Nikita.Sersts
 */
public class FormDBSystemGUI extends javax.swing.JFrame {

    /**
     * Creates new form FormDBSystemGUI
     */
    public FormDBSystemGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginDialogWin = new javax.swing.JDialog();
        txtLoginHeading = new javax.swing.JLabel();
        txtLoginName = new javax.swing.JLabel();
        fieldLoginPersonalCode = new javax.swing.JTextField();
        txtLoginSurname = new javax.swing.JLabel();
        fieldLoginName = new javax.swing.JTextField();
        txtLoginPersonalCode = new javax.swing.JLabel();
        fieldLoginSurname = new javax.swing.JTextField();
        txtLoginPassword = new javax.swing.JLabel();
        fieldLoginPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        RegisterDialogWin = new javax.swing.JDialog();
        txtRegisterHeading = new javax.swing.JLabel();
        txtRegisterName = new javax.swing.JLabel();
        fieldRegisterPersonalCode = new javax.swing.JTextField();
        txtRegisterSurname = new javax.swing.JLabel();
        fieldRegisterName = new javax.swing.JTextField();
        txtRegisterPersonalCode = new javax.swing.JLabel();
        fieldRegisterSurname = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JLabel();
        txtRegisterRole = new javax.swing.JLabel();
        fieldRegisterPassword = new javax.swing.JTextField();
        comboBoxRegisterRole = new javax.swing.JComboBox<>();
        btnRegisterBack = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnLoginForm = new javax.swing.JButton();
        txtGreeting = new javax.swing.JLabel();

        LoginDialogWin.setTitle("Ielagošana");

        txtLoginHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLoginHeading.setForeground(new java.awt.Color(23, 71, 122));
        txtLoginHeading.setText("Ielogošanās sistēmā");

        txtLoginName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLoginName.setForeground(new java.awt.Color(23, 71, 122));
        txtLoginName.setText("Vārds");

        fieldLoginPersonalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLoginPersonalCodeActionPerformed(evt);
            }
        });

        txtLoginSurname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLoginSurname.setForeground(new java.awt.Color(23, 71, 122));
        txtLoginSurname.setText("Uzvārds");

        fieldLoginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLoginNameActionPerformed(evt);
            }
        });

        txtLoginPersonalCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLoginPersonalCode.setForeground(new java.awt.Color(23, 71, 122));
        txtLoginPersonalCode.setText("Personas kods");

        fieldLoginSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLoginSurnameActionPerformed(evt);
            }
        });

        txtLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLoginPassword.setForeground(new java.awt.Color(23, 71, 122));
        txtLoginPassword.setText("Parole");

        fieldLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLoginPasswordActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(20, 80, 140));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ielogoties");

        javax.swing.GroupLayout LoginDialogWinLayout = new javax.swing.GroupLayout(LoginDialogWin.getContentPane());
        LoginDialogWin.getContentPane().setLayout(LoginDialogWinLayout);
        LoginDialogWinLayout.setHorizontalGroup(
            LoginDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDialogWinLayout.createSequentialGroup()
                .addGroup(LoginDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginDialogWinLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(txtLoginHeading))
                    .addGroup(LoginDialogWinLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(LoginDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoginName)
                            .addComponent(txtLoginSurname)
                            .addComponent(fieldLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(fieldLoginPersonalCode)
                            .addComponent(txtLoginPersonalCode)
                            .addComponent(fieldLoginSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(txtLoginPassword)
                            .addComponent(fieldLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        LoginDialogWinLayout.setVerticalGroup(
            LoginDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginDialogWinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLoginHeading)
                .addGap(38, 38, 38)
                .addComponent(txtLoginName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtLoginSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldLoginSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoginPersonalCode)
                .addGap(12, 12, 12)
                .addComponent(fieldLoginPersonalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLoginPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        RegisterDialogWin.setTitle("Ielagošana");

        txtRegisterHeading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRegisterHeading.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterHeading.setText("Reģistrēšanas sistēmā");

        txtRegisterName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegisterName.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterName.setText("Vārds");

        fieldRegisterPersonalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegisterPersonalCodeActionPerformed(evt);
            }
        });

        txtRegisterSurname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegisterSurname.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterSurname.setText("Uzvārds");

        fieldRegisterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegisterNameActionPerformed(evt);
            }
        });

        txtRegisterPersonalCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegisterPersonalCode.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterPersonalCode.setText("Personas kods");

        fieldRegisterSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegisterSurnameActionPerformed(evt);
            }
        });

        txtRegisterPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegisterPassword.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterPassword.setText("Parole");

        txtRegisterRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtRegisterRole.setForeground(new java.awt.Color(23, 71, 122));
        txtRegisterRole.setText("Loma");

        fieldRegisterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegisterPasswordActionPerformed(evt);
            }
        });

        comboBoxRegisterRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pacients", "Ārsts", "Administrators" }));
        comboBoxRegisterRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRegisterRoleActionPerformed(evt);
            }
        });

        btnRegisterBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterBack.setForeground(new java.awt.Color(23, 71, 122));
        btnRegisterBack.setText("Atgriezties");
        btnRegisterBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 71, 122)));

        btnRegister.setBackground(new java.awt.Color(20, 80, 140));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Reģistrēt");

        javax.swing.GroupLayout RegisterDialogWinLayout = new javax.swing.GroupLayout(RegisterDialogWin.getContentPane());
        RegisterDialogWin.getContentPane().setLayout(RegisterDialogWinLayout);
        RegisterDialogWinLayout.setHorizontalGroup(
            RegisterDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDialogWinLayout.createSequentialGroup()
                .addGroup(RegisterDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterDialogWinLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(txtRegisterHeading))
                    .addGroup(RegisterDialogWinLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(RegisterDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegisterBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegisterDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRegisterName)
                                .addComponent(txtRegisterSurname)
                                .addComponent(fieldRegisterName, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(fieldRegisterPersonalCode)
                                .addComponent(txtRegisterPersonalCode)
                                .addComponent(fieldRegisterSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(txtRegisterPassword)
                                .addComponent(txtRegisterRole)
                                .addComponent(fieldRegisterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addComponent(comboBoxRegisterRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        RegisterDialogWinLayout.setVerticalGroup(
            RegisterDialogWinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDialogWinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegisterHeading)
                .addGap(38, 38, 38)
                .addComponent(txtRegisterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldRegisterName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtRegisterSurname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldRegisterSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegisterPersonalCode)
                .addGap(12, 12, 12)
                .addComponent(fieldRegisterPersonalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegisterPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtRegisterRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxRegisterRole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog2.setPreferredSize(new java.awt.Dimension(600, 450));

        jButton5.setForeground(new java.awt.Color(23, 71, 122));
        jButton5.setText("\t🏠 Sākums");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 71, 122)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setForeground(new java.awt.Color(23, 71, 122));
        jButton9.setText("\t👥Pacienti");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 71, 122)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setForeground(new java.awt.Color(23, 71, 122));
        jButton10.setText("\t📅 Vizītes");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 71, 122)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setForeground(new java.awt.Color(23, 71, 122));
        jButton11.setText("Iziet");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 71, 122)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(23, 71, 122));
        jLabel1.setText("Name ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 71, 122));
        jLabel2.setText("Labdien, name !");

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Loma");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialog2Layout.createSequentialGroup()
                                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)))
                        .addContainerGap(249, Short.MAX_VALUE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(53, 53, 53))))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));

        BtnLoginForm.setBackground(new java.awt.Color(20, 80, 140));
        BtnLoginForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLoginForm.setForeground(new java.awt.Color(255, 255, 255));
        BtnLoginForm.setText("Ielogoties");

        txtGreeting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGreeting.setForeground(new java.awt.Color(23, 71, 122));
        txtGreeting.setText("Labdien!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(BtnLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(txtGreeting)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtGreeting)
                .addGap(87, 87, 87)
                .addComponent(BtnLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLoginPersonalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLoginPersonalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLoginPersonalCodeActionPerformed

    private void fieldLoginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLoginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLoginNameActionPerformed

    private void fieldLoginSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLoginSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLoginSurnameActionPerformed

    private void fieldLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLoginPasswordActionPerformed

    private void fieldRegisterPersonalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegisterPersonalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegisterPersonalCodeActionPerformed

    private void fieldRegisterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegisterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegisterNameActionPerformed

    private void fieldRegisterSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegisterSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegisterSurnameActionPerformed

    private void fieldRegisterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegisterPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegisterPasswordActionPerformed

    private void comboBoxRegisterRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRegisterRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRegisterRoleActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDBSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDBSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDBSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDBSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDBSystemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoginForm;
    private javax.swing.JDialog LoginDialogWin;
    private javax.swing.JDialog RegisterDialogWin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterBack;
    private javax.swing.JComboBox<String> comboBoxRegisterRole;
    private javax.swing.JTextField fieldLoginName;
    private javax.swing.JTextField fieldLoginPassword;
    private javax.swing.JTextField fieldLoginPersonalCode;
    private javax.swing.JTextField fieldLoginSurname;
    private javax.swing.JTextField fieldRegisterName;
    private javax.swing.JTextField fieldRegisterPassword;
    private javax.swing.JTextField fieldRegisterPersonalCode;
    private javax.swing.JTextField fieldRegisterSurname;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtGreeting;
    private javax.swing.JLabel txtLoginHeading;
    private javax.swing.JLabel txtLoginName;
    private javax.swing.JLabel txtLoginPassword;
    private javax.swing.JLabel txtLoginPersonalCode;
    private javax.swing.JLabel txtLoginSurname;
    private javax.swing.JLabel txtRegisterHeading;
    private javax.swing.JLabel txtRegisterName;
    private javax.swing.JLabel txtRegisterPassword;
    private javax.swing.JLabel txtRegisterPersonalCode;
    private javax.swing.JLabel txtRegisterRole;
    private javax.swing.JLabel txtRegisterSurname;
    // End of variables declaration//GEN-END:variables
}
